import json
import os
import torch
import numpy as np
from train import PolicyNetwork, board_to_tensor
from environment import PegSolitaireEnv

def evaluate_ope(trajectories_file="trajectories.json", model_path="peg_solitaire_policy.pth", gamma=0.99):
    """
    Evaluates the trained Policy Network using Off-Policy Evaluation (OPE).
    Specifically calculates the Step-wise Importance Sampling (IS) Estimator.
    
    This evaluates if the new model is statistically "better" than the historical
    behavior that generated the dataset, WITHOUT using the environment simulator.
    """
    if not os.path.exists(trajectories_file):
        print(f"Dataset {trajectories_file} not found.")
        return
        
    try:
        model = PolicyNetwork()
        model.load_state_dict(torch.load(model_path))
        model.eval()
    except Exception as e:
        print(f"Failed to load model from {model_path}: {e}")
        return

    with open(trajectories_file, 'r') as f:
        data = json.load(f)
        
    print(f"Loaded {len(data)} trajectories for Off-Policy Evaluation.")
    
    # We need a behavioral policy (pi_old) to calculate Importance Sampling.
    # In a real RecSys, this is logged at serving time.
    # Here, we approximate pi_old as a uniform distribution over legal moves
    # since our dataset was generated by pure random rollout (and some DFS).
    env = PegSolitaireEnv()
    
    total_is_estimate = 0.0
    total_historical_return = 0.0
    valid_trajectories = 0
    
    with torch.no_grad():
        for game in data:
            outcome = game.get('outcome', 32)
            
            # Reconstruct the historical final reward
            if outcome == 1:
                final_reward = 100.0
            else:
                final_reward = -float(outcome * 2)
                
            moves = game['moves']
            if len(moves) == 0: continue
            
            # Calculate the true discounted return of the historical trajectory
            historical_return = 0.0
            R = final_reward
            returns = []
            for _ in reversed(moves):
                returns.insert(0, R)
                R = -1.0 + gamma * R
                
            historical_return = returns[0] # The return from t=0
            total_historical_return += historical_return
            
            # Calculate the Importance Sampling Estimate for this trajectory
            # V(pi_new) = sum( (pi_new(a|s) / pi_old(a|s)) * Reward )
            
            trajectory_is_estimate = 0.0
            cumulative_rho = 1.0 # Importance weight product (rho)
            
            # We reconstruct the board purely to get the number of legal moves for pi_old
            env.reset()
            # If the state in the JSON doesn't exactly match the env reset, we'd need
            # to forcefully set the env.board. For our random data, it starts at the beginning.
            
            for t, move in enumerate(moves):
                state = board_to_tensor(move['state'])
                
                # Get New Policy Probability: pi_new(a|s)
                logits = model(state.unsqueeze(0))
                probs = torch.softmax(logits, dim=1)
                
                r = move['action']['row']
                c = move['action']['col']
                d = move['action']['dir']
                action_idx = (r * 7 * 4) + (c * 4) + d
                
                pi_new_prob = probs[0, action_idx].item()
                
                # Get Old Documented Probability: pi_old(a|s)
                # For our synthetic data generator, it chose uniformly from legal moves.
                legal_moves = env.get_legal_actions()
                if len(legal_moves) > 0:
                    pi_old_prob = 1.0 / len(legal_moves)
                else:
                    pi_old_prob = 1.0 # Should not happen if game wasn't over
                
                # Importance Weight for this step
                rho_t = pi_new_prob / (pi_old_prob + 1e-8)
                
                # Multiply into the cumulative product. 
                # (Note: Step-wise IS uses cumulative rho up to step t)
                cumulative_rho *= rho_t
                
                # Add to the trajectory estimate: rho_0:t * r_t
                # In our environment, step reward is always -1.0 except the final step
                step_reward = -1.0 if t < len(moves) - 1 else final_reward
                
                trajectory_is_estimate += cumulative_rho * step_reward * (gamma ** t)
                
                # Advance the environment to get the legal moves for the NEXT step
                if len(legal_moves) > 0:
                    try:
                        env.step((r, c, d))
                    except:
                        pass # Ignore if state mismatch
                
            total_is_estimate += trajectory_is_estimate
            valid_trajectories += 1
            
    if valid_trajectories == 0:
        print("No valid trajectories found to evaluate.")
        return
        
    avg_historical = total_historical_return / valid_trajectories
    avg_is_estimate = total_is_estimate / valid_trajectories
    
    print("\n========= Off-Policy Evaluation (OPE) Results =========")
    print(f"Evaluated on {valid_trajectories} offline trajectories.")
    print(f"1. Average Historical Return (Old Policy):  {avg_historical:.2f}")
    print(f"2. Importance Sampling Estimate (New Policy): {avg_is_estimate:.2f}")
    print("=======================================================")
    
    if avg_is_estimate > avg_historical:
        print("\n✅ Conclusion: The new model (pi_new) is estimated to be BETTER than the historical policy!")
    else:
        print("\n❌ Conclusion: The new model is estimated to be WORSE than the historical policy.")
        print("   (This is common with Behavioral Cloning heavily weighting losing games).")
        
    print("\nNote on Importance Sampling (IS) Variance:")
    print("   Because IS multiplies probability ratios across many time steps,")
    print("   the final estimate can suffer from extreme variance if pi_new diverts")
    print("   heavily from pi_old. In industry, methods like Weighted IS (WIS) or")
    print("   Doubly Robust (DR) are used to clip these exploding weights.")

if __name__ == "__main__":
    evaluate_ope()
